# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          boychaboy
baseurl:        "http://boychaboy.github.io"
url:            "http://boychaboy.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         boychaboy
  url:          http://boychaboy.github.io/
  email:        iamboychaboy@gmail.com  
  github:       boychaboy

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/boychaboy/boychaboy.github.io
